import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { InfoHint } from "./InfoHint";
import { formatCurrency, formatDate, formatDaysSince, statusLabel } from "../lib/format";
export function CustomerTable({ customers }) {
    if (!customers.length) {
        return (_jsx("div", { className: "panel table-panel empty-panel", children: _jsx("div", { className: "empty-state", children: "Nenhum cliente encontrado para esse filtro." }) }));
    }
    return (_jsx("div", { className: "panel table-panel", children: _jsxs("table", { className: "data-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Cliente" }), _jsx("th", { children: "Status" }), _jsx("th", { children: "Ultima compra" }), _jsx("th", { children: "Tempo sem comprar" }), _jsx("th", { children: "Pedidos" }), _jsx("th", { children: "Ticket medio" }), _jsx("th", { children: "Total gasto" }), _jsx("th", { children: "Rotulos" }), _jsx("th", { children: _jsxs("span", { className: "header-with-info", children: ["Prioridade", _jsx(InfoHint, { text: "Pontuacao de prioridade: 40% recencia, 25% valor do cliente, 20% queda de frequencia e 15% compra prevista vencida." })] }) }), _jsx("th", { children: "Insight" })] }) }), _jsx("tbody", { children: customers.map((customer) => (_jsxs("tr", { children: [_jsx("td", { children: _jsxs(Link, { className: "table-link", to: `/clientes/${customer.id}`, children: [_jsx("strong", { children: customer.displayName }), _jsx("span", { children: customer.customerCode })] }) }), _jsx("td", { children: _jsx("span", { className: `status-badge status-${customer.status.toLowerCase()}`, children: statusLabel(customer.status) }) }), _jsx("td", { children: formatDate(customer.lastPurchaseAt) }), _jsx("td", { children: formatDaysSince(customer.daysSinceLastPurchase) }), _jsx("td", { children: customer.totalOrders }), _jsx("td", { children: formatCurrency(customer.avgTicket) }), _jsx("td", { children: formatCurrency(customer.totalSpent) }), _jsx("td", { children: _jsx("div", { className: "tag-row compact", children: customer.labels.length ? (customer.labels.map((label) => (_jsx("span", { className: "tag", style: { background: `${label.color}14`, color: label.color, borderColor: `${label.color}33` }, children: label.name }, label.id)))) : (_jsx("span", { className: "muted-copy", children: "Sem r\u00F3tulo" })) }) }), _jsx("td", { children: customer.priorityScore.toFixed(1) }), _jsx("td", { children: customer.primaryInsight ?? "Sem alerta" })] }, customer.id))) })] }) }));
}
