import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { formatCurrency, formatDate, formatDaysSince, formatPercent } from "../lib/format";
function sourceLabel(row) {
    return row.primarySource === "CREDIT_BALANCE" ? "Saldo a favor" : "Credito livre";
}
export function CustomerOpportunityTable({ rows, emptyMessage }) {
    if (!rows.length) {
        return (_jsx("div", { className: "panel table-panel empty-panel", children: _jsx("div", { className: "empty-state", children: emptyMessage }) }));
    }
    return (_jsx("div", { className: "panel table-panel", children: _jsx("div", { className: "table-scroll", children: _jsxs("table", { className: "data-table opportunity-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Cliente" }), _jsx("th", { children: "Origem" }), _jsx("th", { children: "Valor alvo" }), _jsx("th", { children: "Sugestao" }), _jsx("th", { children: "Cobertura" }), _jsx("th", { children: "Mix em estoque" }), _jsx("th", { children: "Ultima compra" }), _jsx("th", {})] }) }), _jsx("tbody", { children: rows.map((row) => (_jsxs("tr", { className: row.primarySource === "CREDIT_BALANCE" ? "opportunity-row-priority" : "opportunity-row-credit", children: [_jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: row.customerDisplayName }), _jsx("span", { children: row.customerCode })] }) }), _jsx("td", { children: _jsx("span", { className: `credit-action-pill ${row.primarySource === "CREDIT_BALANCE" ? "tone-success" : "tone-info"}`, children: sourceLabel(row) }) }), _jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: formatCurrency(row.targetAmount) }), _jsx("span", { children: row.creditBalanceAmount > 0 ? `Saldo ${formatCurrency(row.creditBalanceAmount)}` : `Credito ${formatCurrency(row.availableCreditAmount)}` })] }) }), _jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: formatCurrency(row.suggestedAmount) }), _jsxs("span", { children: ["Gap ", formatCurrency(row.remainingGapAmount)] })] }) }), _jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: formatPercent(row.coverageRatio) }), _jsxs("span", { children: [row.suggestedLineCount, " itens sugeridos / ", row.matchedProductCount, " do mix"] })] }) }), _jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: row.topModelsInStock[0] ?? "Sem match" }), _jsx("span", { children: row.topModelsInStock.slice(1).join(", ") || "Sem outros modelos no topo" })] }) }), _jsx("td", { children: _jsxs("div", { className: "table-link", children: [_jsx("strong", { children: formatDate(row.lastPurchaseAt) }), _jsx("span", { children: formatDaysSince(row.daysSinceLastPurchase) })] }) }), _jsx("td", { className: "credit-cell-action", children: _jsx(Link, { className: "primary-button small-button", to: `/clientes/${row.customerId}`, children: "Montar abordagem" }) })] }, row.customerId))) })] }) }) }));
}
