import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertTriangle, MessageSquare, TrendingUp, Clock, Ghost } from "lucide-react";
function MetricCard({ title, value, subtitle, icon: Icon, trend, color }) {
    return (_jsxs("div", { className: "wa-metric-card", children: [_jsx("div", { className: "wa-metric-icon", style: { backgroundColor: color ? `${color}15` : undefined }, children: _jsx(Icon, { size: 22, style: { color } }) }), _jsxs("div", { className: "wa-metric-content", children: [_jsx("span", { className: "wa-metric-title", children: title }), _jsxs("div", { className: "wa-metric-value-row", children: [_jsx("span", { className: "wa-metric-value", children: value }), trend && (_jsxs("span", { className: `wa-metric-trend ${trend.positive ? "positive" : "negative"}`, children: [trend.positive ? "+" : "", trend.value, "%"] }))] }), subtitle && _jsx("span", { className: "wa-metric-subtitle", children: subtitle })] })] }));
}
export function EventsSummaryPanel({ metrics }) {
    if (!metrics)
        return null;
    const { summary, operationalEfficiency } = metrics;
    return (_jsxs("div", { className: "wa-metrics-grid", children: [_jsx(MetricCard, { title: "Total de Eventos", value: summary.totalEvents, subtitle: `${summary.totalEvents - summary.unresolvedEvents} resolvidos`, icon: MessageSquare, color: "#3b82f6" }), _jsx(MetricCard, { title: "Alertas Cr\u00EDticos", value: (summary.bySeverity?.CRITICAL || 0) + (summary.bySeverity?.HIGH || 0), subtitle: "Risco alto detectado", icon: AlertTriangle, color: "#ef4444" }), _jsx(MetricCard, { title: "Sentimento M\u00E9dio", value: Number(summary.averageSentiment ?? 0).toFixed(1), subtitle: Number(summary.averageSentiment ?? 0) > 0.3 ? "Predominantemente positivo" : Number(summary.averageSentiment ?? 0) < -0.3 ? "Atenção necessária" : "Neutro", icon: TrendingUp, color: "#10b981" }), _jsx(MetricCard, { title: "Resolu\u00E7\u00E3o M\u00E9dia", value: `${Number(operationalEfficiency.averageResolutionTimeHours ?? 0).toFixed(1)}h`, subtitle: "Tempo de encerramento", icon: Clock, color: "#8b5cf6" }), _jsx(MetricCard, { title: "Gargalos", value: operationalEfficiency.bottleneckAgents?.length ?? 0, subtitle: "Agentes com pend\u00EAncias", icon: Ghost, color: "#f59e0b" })] }));
}
