import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Calendar, ChevronDown, X } from "lucide-react";
export function EventsFilters({ filters, onChange }) {
    const handleTypeChange = (type) => {
        const current = filters.eventType ? filters.eventType.split(",") : [];
        const next = current.includes(type)
            ? current.filter(t => t !== type)
            : [...current, type];
        onChange({ ...filters, eventType: next.join(",") || undefined });
    };
    const clearFilters = () => {
        onChange({ search: filters.search });
    };
    return (_jsxs("div", { className: "wa-events-filters", children: [_jsxs("div", { className: "wa-filter-search", children: [_jsx(Search, { size: 18 }), _jsx("input", { type: "text", placeholder: "Pesquisar em eventos ou clientes...", value: filters.search || "", onChange: (e) => onChange({ ...filters, search: e.target.value }) })] }), _jsxs("div", { className: "wa-filter-group", children: [_jsxs("label", { className: "wa-filter-select", children: [_jsxs("select", { value: filters.severity || "", onChange: (e) => onChange({ ...filters, severity: e.target.value || undefined }), children: [_jsx("option", { value: "", children: "Severidade: Todas" }), _jsx("option", { value: "CRITICAL", children: "Cr\u00EDtico / Urgente" }), _jsx("option", { value: "HIGH", children: "Alta" }), _jsx("option", { value: "MODERATE", children: "Moderada" }), _jsx("option", { value: "LOW", children: "Baixa" })] }), _jsx(ChevronDown, { size: 16 })] }), _jsxs("label", { className: "wa-filter-select", children: [_jsxs("select", { value: filters.eventType || "", onChange: (e) => onChange({ ...filters, eventType: e.target.value || undefined }), children: [_jsx("option", { value: "", children: "Tipo: Todos" }), _jsx("option", { value: "RISK", children: "Risco" }), _jsx("option", { value: "COMPLAINT", children: "Reclama\u00E7\u00E3o" }), _jsx("option", { value: "PRAISE", children: "Elogio" }), _jsx("option", { value: "QUESTION", children: "D\u00FAvida" }), _jsx("option", { value: "ESCALATION", children: "Escala\u00E7\u00E3o" })] }), _jsx(ChevronDown, { size: 16 })] }), _jsxs("label", { className: "wa-filter-select", children: [_jsxs("select", { value: filters.resolved || "", onChange: (e) => onChange({ ...filters, resolved: e.target.value || undefined }), children: [_jsx("option", { value: "", children: "Status: Todos" }), _jsx("option", { value: "false", children: "Pendente" }), _jsx("option", { value: "true", children: "Resolvido" })] }), _jsx(ChevronDown, { size: 16 })] }), _jsxs("div", { className: "wa-filter-date", children: [_jsx(Calendar, { size: 16 }), _jsx("input", { type: "date", value: filters.dateFrom || "", onChange: (e) => onChange({ ...filters, dateFrom: e.target.value || undefined }) }), _jsx("span", { children: "at\u00E9" }), _jsx("input", { type: "date", value: filters.dateTo || "", onChange: (e) => onChange({ ...filters, dateTo: e.target.value || undefined }) })] }), Object.keys(filters).length > 0 && (_jsxs("button", { type: "button", className: "wa-clear-filters", onClick: clearFilters, children: [_jsx(X, { size: 16 }), "Limpar"] }))] })] }));
}
