import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertTriangle, CircleHelp, Clock, FilterX, Inbox, Target, TrendingUp, UsersRound, } from "lucide-react";
function MetricCard({ title, value, subtitle, icon: Icon, trend, color }) {
    return (_jsxs("div", { className: "wa-metric-card", children: [_jsx("div", { className: "wa-metric-icon", style: { backgroundColor: color ? `${color}15` : undefined }, children: _jsx(Icon, { size: 22, style: { color } }) }), _jsxs("div", { className: "wa-metric-content", children: [_jsx("span", { className: "wa-metric-title", children: title }), _jsxs("div", { className: "wa-metric-value-row", children: [_jsx("span", { className: "wa-metric-value", children: value }), trend && (_jsxs("span", { className: `wa-metric-trend ${trend.positive ? "positive" : "negative"}`, children: [trend.positive ? "+" : "", trend.value, "%"] }))] }), subtitle && _jsx("span", { className: "wa-metric-subtitle", children: subtitle })] })] }));
}
export function EventsSummaryPanel({ metrics }) {
    if (!metrics)
        return null;
    const { summary, operationalEfficiency } = metrics;
    const executive = metrics.executiveSummary;
    const actionableEvents = summary.actionRequiredEvents ?? summary.unresolvedEvents;
    const sentiment = summary.averageSentiment ?? 0;
    return (_jsxs("div", { className: "wa-metrics-grid", children: [_jsx(MetricCard, { title: "Acao Necessaria", value: actionableEvents, subtitle: "Pendencias reais no periodo", icon: Inbox, color: "#3b82f6" }), _jsx(MetricCard, { title: "Alertas Criticos", value: (summary.bySeverity?.CRITICAL || 0) + (summary.bySeverity?.HIGH || 0), subtitle: "Risco alto ou escalacao", icon: AlertTriangle, color: "#ef4444" }), _jsx(MetricCard, { title: "Oportunidades", value: summary.opportunitiesCount ?? executive?.opportunitiesCount ?? 0, subtitle: `${executive?.unansweredOpportunitiesCount ?? 0} sem resposta ha mais de 2h`, icon: Target, color: "#2563eb" }), _jsx(MetricCard, { title: "Duvidas", value: summary.questionCount ?? executive?.questionCount ?? 0, subtitle: "Perguntas que pedem retorno", icon: CircleHelp, color: "#7c3aed" }), _jsx(MetricCard, { title: "Ruido Filtrado", value: summary.filteredNoiseCount ?? executive?.filteredNoiseCount ?? 0, subtitle: "Saudacoes, respostas curtas e listas", icon: FilterX, color: "#64748b" }), _jsx(MetricCard, { title: "Sentimento Medio", value: sentiment.toFixed(1), subtitle: sentiment > 0.3 ? "Predominantemente positivo" : sentiment < -0.3 ? "Atencao necessaria" : "Neutro", icon: TrendingUp, color: "#10b981" }), _jsx(MetricCard, { title: "Resolucao Media", value: `${(operationalEfficiency.averageResolutionTimeHours ?? 0).toFixed(1)}h`, subtitle: "Tempo de encerramento", icon: Clock, color: "#8b5cf6" }), _jsx(MetricCard, { title: "Gargalos", value: operationalEfficiency.bottleneckAgents?.length ?? 0, subtitle: "Agentes com fila acionavel", icon: UsersRound, color: "#f59e0b" })] }));
}
